apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-test
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secret/data/some-test/test"
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/devops893/helm-2.git
    targetRevision: main
    helm:
      values: |
        name: some-test324
        address: <test>
